#!/usr/bin/env python
"""Run Checkpoint 03C.4 leakage-safe nested stacking evaluation."""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from geocebada.evaluation import (
    build_competition_representation_specs,
    evaluate_nested_stacking,
    summarize_stacking_results,
)
from geocebada.features import join_agronomic_features, join_empirical_features
from geocebada.paths import find_project_root

ROOT = Path(__file__).resolve().parents[1]


def _load_yaml(path: Path) -> dict[str, Any]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected YAML mapping in {path}.")
    return payload


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in {path}.")
    return payload


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _parse_csv_list(value: str | None) -> list[str] | None:
    if value is None:
        return None
    items = [item.strip() for item in value.split(",") if item.strip()]
    return items or None


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> list[str]:
    lines = [
        "| " + " | ".join(columns) + " |",
        "|" + "|".join(["---"] * len(columns)) + "|",
    ]
    for row in frame.loc[:, columns].itertuples(index=False, name=None):
        values: list[str] = []
        for value in row:
            if isinstance(value, float):
                values.append("" if pd.isna(value) else f"{value:.4f}")
            else:
                values.append(str(value).replace("|", "\\|"))
        lines.append("| " + " | ".join(values) + " |")
    return lines


def _render_report(
    *,
    report: dict[str, Any],
    protocol_summary: pd.DataFrame,
    robustness: pd.DataFrame,
) -> str:
    lines = [
        "# Checkpoint 03C.4 — Leakage-safe nested stacking",
        "",
        f"Generated: {report['generated_at']}",
        "",
        "## Scope",
        "",
        "- active feature track: **competition only**",
        "- outer evaluation: frozen Checkpoint 02 folds",
        f"- level-1 cross-fitting: **{report['level1_folds']} folds**",
        (
            "- base tuning inside each level-1 training split: "
            f"**{report['base_tuning_folds']} folds**"
        ),
        f"- outer-refit base tuning: **{report['outer_refit_tuning_folds']} folds**",
        f"- meta tuning: **{report['meta_tuning_folds']} folds**",
        f"- CatBoost execution: **{report['catboost_task_type_final']}**",
        "- hidden prediction targets used: **no**",
        "- final 59 predictions generated: **no**",
        "",
        "Each level-1 training prediction is generated by a base learner that neither",
        "fits nor tunes on that row. The frozen outer fold remains untouched until",
        "the complete base-plus-stacker procedure predicts it.",
        "",
        "The current CV is development validation: it is used to guide modeling",
        "decisions, so its minimum should not be described as an untouched final-test",
        "error. The 59 hidden challenge parcels remain unscored.",
        "",
        "## Cross-protocol robustness",
        "",
    ]
    lines.extend(
        _markdown_table(
            robustness,
            [
                "meta_model",
                "state_oof_rmse",
                "grouped_oof_rmse",
                "mean_oof_rmse",
                "worst_protocol_rmse",
                "worst_protocol_rmse_kg_ha",
                "protocol_gap",
            ],
        )
    )

    for protocol in report["protocols"]:
        lines.extend(["", f"## {protocol}", ""])
        subset = protocol_summary.loc[
            protocol_summary["protocol"].eq(protocol)
        ].sort_values(["oof_rmse", "meta_model"])
        lines.extend(
            _markdown_table(
                subset,
                [
                    "meta_model",
                    "oof_rmse",
                    "oof_rmse_kg_ha",
                    "oof_nrmse_pct",
                    "oof_mae",
                    "oof_r2",
                    "fold_rmse_mean",
                    "fold_rmse_std",
                ],
            )
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- RMSE remains reported in ton/ha; oof_rmse_kg_ha multiplies it by 1,000",
            "  only for interpretability. Rescaling does not change model ranking.",
            "- PCA+Ridge base learners are included as explicit dimensionality-reduction",
            "  experiments; their PCA and tuning remain inside the appropriate folds.",
            "- ConvexAll learns nonnegative weights summing to one from honest level-1",
            "  OOF predictions.",
            "- Ridge, ElasticNet, Huber, ExtraTrees and HistGradientBoosting stackers",
            "  are evaluated as low-dimensional level-1 learners.",
            "- Do not select by state-stratified RMSE alone; municipality-grouped",
            "  robustness remains a first-class criterion.",
            "",
        ]
    )
    return "\n".join(lines)


def run_checkpoint_03c4(
    *,
    root: Path,
    config: dict[str, Any],
    selected_base_candidates: list[str] | None = None,
    selected_meta_models: list[str] | None = None,
    selected_protocols: list[str] | None = None,
    catboost_task_type: str | None = None,
) -> dict[str, Any]:
    """Run Checkpoint 03C.4 and write reproducible stacking artifacts."""

    inputs = config["inputs"]
    outputs = config["outputs"]

    base_dir = root / str(inputs["base_directory"])
    agronomic_dir = root / str(inputs["agronomic_directory"])
    empirical_dir = root / str(inputs["empirical_directory"])

    base_table_path = base_dir / str(inputs["base_table"])
    agronomic_table_path = agronomic_dir / str(inputs["agronomic_table"])
    empirical_table_path = empirical_dir / str(inputs["empirical_table"])
    folds_path = root / str(inputs["frozen_folds"])
    c2_config_path = root / str(inputs["checkpoint03c2_config"])
    empirical_config_path = root / str(inputs["empirical_config"])

    base = pd.read_csv(base_table_path)
    agronomic = pd.read_csv(agronomic_table_path)
    empirical = pd.read_csv(empirical_table_path)
    folds = pd.read_csv(folds_path)

    joined = join_agronomic_features(base, agronomic)
    joined = join_empirical_features(joined, empirical)

    manifests = {
        "base": _load_json(base_dir / str(inputs["base_manifest"])),
        "agronomic": _load_json(
            agronomic_dir / str(inputs["agronomic_manifest"])
        ),
        "empirical": _load_json(
            empirical_dir / str(inputs["empirical_manifest"])
        ),
    }
    checkpoint03c2_config = _load_yaml(c2_config_path)
    empirical_config = _load_yaml(empirical_config_path)
    representations = build_competition_representation_specs(
        joined=joined,
        manifests=manifests,
        config=checkpoint03c2_config,
        empirical_config=empirical_config,
    )

    (
        base_outer,
        meta_training,
        stack_oof,
        base_search,
        meta_search,
        outer_metrics,
        coefficients,
        actual_catboost_task,
    ) = evaluate_nested_stacking(
        joined=joined,
        folds=folds,
        representations=representations,
        checkpoint03c2_config=checkpoint03c2_config,
        config=config,
        empirical_config=empirical_config,
        selected_base_candidates=selected_base_candidates,
        selected_meta_models=selected_meta_models,
        selected_protocols=selected_protocols,
        catboost_task_type_override=catboost_task_type,
    )

    protocol_summary, robustness = summarize_stacking_results(
        outer_metrics,
        stack_oof,
        config,
    )

    output_dir = root / str(outputs["directory"])
    output_dir.mkdir(parents=True, exist_ok=True)
    base_outer.to_csv(
        output_dir / str(outputs["base_outer_predictions"]),
        index=False,
    )
    meta_training.to_csv(
        output_dir / str(outputs["meta_training_predictions"]),
        index=False,
    )
    stack_oof.to_csv(
        output_dir / str(outputs["stack_oof_predictions"]),
        index=False,
    )
    base_search.to_csv(
        output_dir / str(outputs["base_search_results"]),
        index=False,
    )
    meta_search.to_csv(
        output_dir / str(outputs["meta_search_results"]),
        index=False,
    )
    outer_metrics.to_csv(
        output_dir / str(outputs["outer_fold_metrics"]),
        index=False,
    )
    protocol_summary.to_csv(
        output_dir / str(outputs["protocol_summary"]),
        index=False,
    )
    robustness.to_csv(
        output_dir / str(outputs["robustness_summary"]),
        index=False,
    )
    coefficients.to_csv(
        output_dir / str(outputs["stack_coefficients"]),
        index=False,
    )

    identity = config["identity"]
    train_mask = joined[str(identity["split_column"])].eq(
        str(identity["train_value"])
    )
    report = {
        "schema_version": int(config["schema_version"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "stage": str(config["stage"]["name"]),
        "active_track": str(config["scope"]["active_track"]),
        "training_rows": int(train_mask.sum()),
        "total_rows": int(len(joined)),
        "prediction_rows_scored": 0,
        "hidden_prediction_targets_used": False,
        "final_predictions_generated": False,
        "protocols": (
            selected_protocols
            if selected_protocols
            else list(map(str, config["validation"]["outer_protocols"]))
        ),
        "level1_folds": int(config["validation"]["level1_folds"]),
        "base_tuning_folds": int(config["validation"]["base_tuning_folds"]),
        "outer_refit_tuning_folds": int(
            config["validation"]["outer_refit_tuning_folds"]
        ),
        "meta_tuning_folds": int(config["validation"]["meta_tuning_folds"]),
        "base_candidates": (
            selected_base_candidates
            if selected_base_candidates
            else list(map(str, config["base_candidates"].keys()))
        ),
        "meta_models": (
            selected_meta_models
            if selected_meta_models
            else list(map(str, config["meta_models"].keys()))
        ),
        "catboost_task_type_final": actual_catboost_task,
        "source_sha256": {
            "base_table": _sha256(base_table_path),
            "agronomic_table": _sha256(agronomic_table_path),
            "empirical_table": _sha256(empirical_table_path),
            "frozen_folds": _sha256(folds_path),
            "checkpoint03c2_config": _sha256(c2_config_path),
            "empirical_config": _sha256(empirical_config_path),
        },
    }

    (output_dir / str(outputs["run_report_json"])).write_text(
        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (output_dir / str(outputs["run_report_markdown"])).write_text(
        _render_report(
            report=report,
            protocol_summary=protocol_summary,
            robustness=robustness,
        ),
        encoding="utf-8",
    )
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/checkpoint03c4.yaml"),
    )
    parser.add_argument(
        "--base-candidates",
        help="Comma-separated base-candidate subset for debugging.",
    )
    parser.add_argument(
        "--meta-models",
        help="Comma-separated stacker subset for debugging.",
    )
    parser.add_argument(
        "--protocols",
        help="Comma-separated outer-protocol subset for debugging.",
    )
    parser.add_argument(
        "--catboost-task-type",
        choices=("GPU", "CPU"),
        help="Override CatBoost task type. Config defaults to GPU.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.expanduser().resolve()
    if not (root / "pyproject.toml").is_file():
        root = find_project_root(root)

    config_path = args.config if args.config.is_absolute() else root / args.config
    report = run_checkpoint_03c4(
        root=root,
        config=_load_yaml(config_path),
        selected_base_candidates=_parse_csv_list(args.base_candidates),
        selected_meta_models=_parse_csv_list(args.meta_models),
        selected_protocols=_parse_csv_list(args.protocols),
        catboost_task_type=args.catboost_task_type,
    )
    print("Checkpoint 03C.4 nested stacking benchmark: PASS")
    print(f"Training rows: {report['training_rows']}")
    print(f"Base candidates: {len(report['base_candidates'])}")
    print(f"Meta models: {len(report['meta_models'])}")
    print(f"CatBoost task type: {report['catboost_task_type_final']}")
    print("Inspect: reports/checkpoint_03c4/checkpoint_03c4_report.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
