"""Generate docs/FUNCTION_INDEX.md from public symbols in src/geocebada.

Run from anywhere inside the repository:

    python tools/generate_function_index.py

The script uses the Python AST instead of importing project modules, so it does
not require optional geospatial/model dependencies just to build the index.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "src" / "geocebada"
OUTPUT = ROOT / "docs" / "FUNCTION_INDEX.md"


@dataclass(frozen=True)
class Symbol:
    name: str
    kind: str
    module: str
    summary: str
    source: str


def collect_public_symbols(package_root: Path = PACKAGE_ROOT) -> list[Symbol]:
    """Collect public top-level functions and classes from the package source."""

    symbols: list[Symbol] = []
    for path in sorted(package_root.rglob("*.py")):
        if any(part.startswith("_") and part != "__init__.py" for part in path.parts):
            continue
        module = _module_name(path, package_root)
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in tree.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                continue
            if node.name.startswith("_"):
                continue
            doc = ast.get_docstring(node) or ""
            summary = doc.strip().splitlines()[0] if doc.strip() else ""
            symbols.append(
                Symbol(
                    name=node.name,
                    kind="class" if isinstance(node, ast.ClassDef) else "function",
                    module=module,
                    summary=summary,
                    source=str(path.relative_to(ROOT)).replace("\\", "/"),
                )
            )
    return sorted(symbols, key=lambda item: (item.module, item.name))


def render_markdown(symbols: list[Symbol]) -> str:
    """Render a searchable Markdown function/class index."""

    lines = [
        "# Function Index",
        "",
        "> Auto-generated by `python tools/generate_function_index.py`. Do not edit manually.",
        "",
        "Use this file before creating a new helper. Search by function name, module, or purpose",
        "to avoid duplicating functionality that already exists in `src/geocebada/`.",
        "",
        "| Symbol | Kind | Module | Purpose | Source |",
        "|---|---|---|---|---|",
    ]
    for symbol in symbols:
        purpose = symbol.summary.replace("|", "\\|")
        row = (
            f"| `{symbol.name}` | {symbol.kind} | `{symbol.module}` | "
            f"{purpose} | `{symbol.source}` |"
        )
        lines.append(row)
    lines.append("")
    return "\n".join(lines)


def write_function_index(output: Path = OUTPUT) -> Path:
    """Generate and write the repository's Markdown public-symbol index."""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(collect_public_symbols()), encoding="utf-8")
    return output


def _module_name(path: Path, package_root: Path) -> str:
    relative = path.relative_to(package_root)
    parts = list(relative.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(["geocebada", *parts])


if __name__ == "__main__":
    destination = write_function_index()
    print(f"Wrote {destination.relative_to(ROOT)}")
